language: node_js
node_js: 10
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- git config --global user.name "TechPeng"
- git config --global user.email "techgeeker@outlook.com"
- npm install -g hexo-cli
- npm install hexo-deployer-git --save
- export HEXO_DEPLOYER_REPO=https://$GH_TOKEN@github.com/PengBlog/Blog.git
install:
- npm i
script:
- hexo clean
- hexo generate
- hexo deploy
- ./bin/autoissue
