# Blog
keywords: Night Owl
author: TechPeng,techgeeker@outlook.com
# description: Nothing lasts forever.
avatar: /images/logo.png

# Social Accounts
twitter: 
rss: 
weibo: 
instagram: 
github: PengBlog
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 
gitalk:
  on: true
  clientID: 3435888d2bd3cfe2c02f
  clientSecret: bed21e3e3b943d399c500079fb54cfb7071080c9
  repo: Blog
  owner: PengBlog
  admin: TechPeng
  distractionFreeMode: true
  
comment_repo:
  owner: PengBlog
  repo: Blog
  client_id: 3435888d2bd3cfe2c02f
  client_secret: bed21e3e3b943d399c500079fb54cfb7071080c9
  label: 'Gitalk'
