# Blog
keywords: Night Owl
author: TechPeng,techgeeker@outlook.com
# description: Nothing lasts forever.
avatar: /images/logo.png

# Social Accounts
twitter: 
rss: 
weibo: 
instagram: 
github: PengBlog
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 
gitalk:
  on: true
  clientID: 2bed45c2bd5ac82ade57
  clientSecret: 66254b742fd1cfcd27878d0ad8ee07ee68458211
  repo: Blog
  owner: PengBlog
  admin: TechPeng
  distractionFreeMode: true
